export const data = [
  {
    isAccepted: false,
    isDeclined: false,
    name: 'Harry Potter',
    active: '10d',
    button: true,
  },
  {
    isAccepted: false,
    isDeclined: false,
    name: 'Don Quixote',
    active: '4d',
    button: false,
  },
  {
    isAccepted: false,
    isDeclined: false,
    name: 'Joan of Arc',
    active: '7d',
  },
  {
    isAccepted: false,
    isDeclined: false,
    name: 'Rosa Park',
    active: '1d',
  },
  {
    isAccepted: false,
    isDeclined: false,
    name: 'Harry Potter',
    active: '11d',
  },
  {
    isAccepted: false,
    isDeclined: false,
    name: 'Don Quixote',
    active: '9d',
  },
  {
    isAccepted: false,
    isDeclined: false,
    name: 'Joan of Arc',
    active: '7d',
  },
  {
    isAccepted: false,
    isDeclined: false,
    name: 'Rosa Park',
    active: '42d',
  },
  {
    isAccepted: false,
    isDeclined: false,
    name: 'Harry Potter',
    active: '14d',
  },
  {
    isAccepted: false,
    isDeclined: false,
    name: 'Don Quixote',
    active: '42d',
  },
  {
    isAccepted: false,
    isDeclined: false,
    name: 'Joan of Arc',
    active: '23d',
  },
  {
    isAccepted: false,
    isDeclined: false,
    name: 'Rosa Park',
    active: '4d',
  },
  {
    isAccepted: false,
    isDeclined: false,
    name: 'Rosa Park',
    active: '1d',
  },
  {
    isAccepted: false,
    isDeclined: false,
    name: 'Harry Potter',
    active: '11d',
  },
  {
    isAccepted: false,
    isDeclined: false,
    name: 'Don Quixote',
    active: '9d',
  },
  {
    isAccepted: false,
    isDeclined: false,
    name: 'Joan of Arc',
    active: '7d',
  },
  {
    isAccepted: false,
    isDeclined: false,
    name: 'Rosa Park',
    active: '42d',
  },
  {
    isAccepted: false,
    isDeclined: false,
    name: 'Harry Potter',
    active: '14d',
  },
  {
    isAccepted: false,
    isDeclined: false,
    name: 'Don Quixote',
    active: '42d',
  },
  {
    isAccepted: false,
    isDeclined: false,
    name: 'Joan of Arc',
    active: '23d',
  },
  {
    isAccepted: false,
    isDeclined: false,
    name: 'Rosa Park',
    active: '4d',
  },
];

export const profileData = [
  {
    id: 1,
    name: 'anubhav',
    username: 'heyy.anubhav',
  },
  {
    id: 2,
    name: 'satish',
    username: 'heyy.satish',
  },
  {
    id: 3,
    name: 'puja',
    username: 'heyy.puja',
    followButton: true,
  },
  {
    id: 4,
    name: 'pushpa',
    username: 'heyy.pushpa',
    followButton: false,
  },
  {
    id: 5,
    name: 'pradeep',
    username: 'heyy.pradeep',
  },
  {
    id: 6,
    name: 'ayushi',
    username: 'heyy.ayushi',
  },
  {
    id: 7,
    name: 'rahul',
    username: 'heyy.rahul',
  },
  {
    id: 8,
    name: 'arpita',
    username: 'heyy.arpita',
  },
];

export const activityData = [
  {
    isStory: true,
    name: 'anubhav',
    isLiked: true,
    isCommented: false,
    isFollowing: false,
    isButton: true,
    isImage: true,
  },

  {
    isStory: true,
    name: 'pradeep',
    isLiked: false,
    isCommented: true,
    isFollowing: false,
    isButton: false,
    isImage: true,
  },
  {
    isStory: true,
    name: 'sumit',
    isLiked: true,
    isCommented: true,
    isFollowing: false,
    isButton: false,
    isImage: true,
  },
  {
    isStory: true,
    name: 'Swati',
    isLiked: true,
    isCommented: false,
    isFollowing: true,
    isButton: true,
    isImage: false,
  },
  {
    isStory: true,
    name: 'satish',
    isLiked: true,
    isCommented: false,
    isFollowing: true,
    isButton: true,
    isImage: false,
  },
  {
    isStory: true,
    name: 'ajeet',
    isLiked: true,
    isCommented: false,
    isFollowing: false,
    isButton: true,
    isImage: false,
  },
  // {
  //   isStory: true,
  //   name: 'ashish',
  //   isLiked: true,
  //   isCommented: false,
  //   isFollowing: false,
  //   isButton: true,
  //   isImage: false,
  // },
  // {
  //   isStory: true,
  //   name: 'abhi',
  //   isLiked: true,
  //   isCommented: false,
  //   isFollowing: false,
  //   isButton: true,
  //   isImage: false,
  // },
];
export const userData = [
  {
    id: 1,
    name: 'anubhav',
    place: 'indore',
    service: 'mern-stack developer',
    isFollow: true,
    isMark: false,
  },
  {
    id: 2,
    name: 'rahul',
    place: 'lucknow',
    service: 'react-native developer',
    isFollow: true,
    isMark: false,
  },
  {
    id: 3,
    name: 'sachin',
    place: 'kanpur',
    service: 'web developer',
    isFollow: true,
    isMark: false,
  },
  {
    id: 4,
    name: 'pradeep',
    place: 'noida',
    service: 'nodejs developer',
    isFollow: true,
    isMark: false,
  },
  {
    id: 5,
    name: 'swati',
    place: 'lucknow',
    service: 'php developer',
    isFollow: true,
    isMark: false,
  },
  {
    id: 6,
    name: 'sumit',
    place: 'indore',
    service: 'react-native developer',
    isFollow: true,
    isMark: false,
  },
  {
    id: 7,
    name: 'satish',
    place: 'indore',
    service: 'react developer',
    isFollow: true,
    isMark: false,
  },
  {
    id: 8,
    name: 'abhi',
    place: 'lucknow',
    service: 'web developer',
    isFollow: true,
    isMark: false,
  },
  {
    id: 9,
    name: 'puja',
    place: 'gonda',
    service: 'mern-stack developer',
    isFollow: true,
    isMark: false,
  },
  {
    id: 10,
    name: 'luci',
    place: 'goa',
    service: 'devops developer',
    isFollow: true,
    isMark: false,
  },
  {
    id: 11,
    name: 'rohan',
    place: 'noida',
    service: 'salesforce developer',
    isFollow: true,
    isMark: false,
  },
  {
    id: 12,
    name: 'pushpa',
    place: 'delhi',
    service: 'nodejs developer',
    isFollow: true,
    isMark: false,
  },
];
export const filterData = {
  sortList: [
    {isSort: true, sort: 'near you'},
    {isSort: true, sort: 'Reecommended'},
    {isSort: true, sort: 'Related'},
  ],
  categoriesList: [
    {isCategorie: true, categories: 'food'},
    {isCategorie: true, categories: 'shopping'},
    {isCategorie: true, categories: 'dining'},
    {isCategorie: true, categories: 'live now'},
    {isCategorie: true, categories: 'rent'},
    {isCategorie: true, categories: 'sale'},
  ],
};
